# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentity.proto\"\xad\x01\n\x06hrData\x12\r\n\x05hr_id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x11\n\tjob_title\x18\x05 \x01(\t\x12\x17\n\x0flocation_number\x18\x06 \x01(\x05\x12\x15\n\rlocation_name\x18\x07 \x01(\t\x12\x15\n\rmanager_hr_id\x18\x08 \x01(\t\"\xc1\x01\n\x07iamData\x12\r\n\x05hr_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\x11\n\tjob_title\x18\x06 \x01(\t\x12\x17\n\x0flocation_number\x18\x07 \x01(\x05\x12\x15\n\rlocation_name\x18\x08 \x01(\t\x12\x15\n\rmanager_hr_id\x18\t \x01(\t2T\n\x08Identity\x12\"\n\x0bgetIdentity\x12\x07.hrData\x1a\x08.iamData\"\x00\x12$\n\renterIdentity\x12\x07.hrData\x1a\x08.iamData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HRDATA._serialized_start=19
  _HRDATA._serialized_end=192
  _IAMDATA._serialized_start=195
  _IAMDATA._serialized_end=388
  _IDENTITY._serialized_start=390
  _IDENTITY._serialized_end=474
# @@protoc_insertion_point(module_scope)
